# Generated by Django 5.2 on 2025-10-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
