# Generated by Django 5.2 on 2025-10-17 01:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名前")),
                ("mail", models.EmailField(max_length=255, verbose_name="メール")),
                ("gender", models.BooleanField(verbose_name="性別")),
                ("department", models.CharField(max_length=255, verbose_name="部署")),
                ("year", models.IntegerField(default=0, verbose_name="社歴")),
                (
                    "created_at",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="作成日"
                    ),
                ),
            ],
        ),
    ]
