# Generated by Django 5.2 on 2025-10-24 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0004_employee"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
