# Generated by Django 5.2 on 2025-10-28 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0005_delete_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
    ]
