# Generated by Django 5.2 on 2025-10-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0006_remove_post_content"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
