# Generated by Django 5.2 on 2025-10-01 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=31, verbose_name="カテゴリ名")),
            ],
            options={
                "verbose_name_plural": "カテゴリ",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=62, verbose_name="タイトル")),
                ("slug", models.SlugField(verbose_name="URLスラッグ（英語）")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="登録しない場合は、デフォルトのイメージ写真を使用する",
                        upload_to="article_image",
                        verbose_name="記事のイメージ写真",
                    ),
                ),
                ("body", models.TextField(verbose_name="本文")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="1:下書き, 2:公開",
                        verbose_name="公開ステータス",
                    ),
                ),
                ("liked", models.IntegerField(default=0, verbose_name="いいね数")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="削除フラグ"),
                ),
                ("creator", models.CharField(max_length=31, verbose_name="投稿者")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="投稿日時"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        to="test2App.category", verbose_name="カテゴリ"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "記事",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commenter",
                    models.CharField(max_length=31, verbose_name="コメント者名"),
                ),
                ("body", models.TextField(verbose_name="コメント文")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="コメント投稿日時"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="test2App.article",
                        verbose_name="記事",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "コメント",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
